#!/bin/bash

declare line=''

if [[ -p /dev/stdin ]]; then
    while read -r line || [[ -n "${line}" ]]; do
        echo -e "${line^^}" 
    done < /dev/stdin
fi
if (( $# == 1 )); then
    while read -r line || [[ -n "${line}" ]]; do
        echo -e "${line^^}" 
    done < $1
else
    while read -r line || [[ -n "${line}" ]]; do
        echo -e "${line^^}" 
    done <<< "${@}"
fi
